# Generated by Django 4.0.4 on 2022-04-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League_App', '0002_alter_player_batting_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rbi', models.IntegerField()),
                ('batting_average', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='at_bats',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='hits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='home_runs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='batting_average',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
