# Generated by Django 4.0.4 on 2022-04-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League_App', '0003_team_player_at_bats_player_hits_player_home_runs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='batting_average',
        ),
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='rbi',
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='chances',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='doubles',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='errors',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='fielding_percentage',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='putouts',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='player',
            name='triples',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='games_played',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='t_at_bats',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='t_batting_average',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=4),
        ),
        migrations.AddField(
            model_name='team',
            name='t_doubles',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='t_hits',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='t_home_runs',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='t_runs',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='t_triples',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='at_bats',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='hits',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='home_runs',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='player',
            name='rbi',
            field=models.IntegerField(default=None),
        ),
    ]
