# Generated by Django 4.0.4 on 2022-04-12 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League_App', '0006_alter_player_assists_alter_player_at_bats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-last_name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-team_name']},
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', related_query_name='player', to='League_App.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='t_players',
            field=models.ManyToManyField(related_name='players', related_query_name='player', to='League_App.player'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['last_name'], name='League_App__last_na_11960d_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_name'], name='League_App__team_na_2a0b90_idx'),
        ),
    ]
