# Generated by Django 4.0.4 on 2022-04-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League_App', '0007_alter_player_options_alter_team_options_player_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(default='My League', max_length=200)),
            ],
            options={
                'ordering': ['-league_name'],
            },
        ),
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='at_bats',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batting_average',
        ),
        migrations.RemoveField(
            model_name='player',
            name='chances',
        ),
        migrations.RemoveField(
            model_name='player',
            name='doubles',
        ),
        migrations.RemoveField(
            model_name='player',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='player',
            name='fielding_percentage',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='player',
            name='home_runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='putouts',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rbi',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='triples',
        ),
        migrations.RemoveField(
            model_name='team',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='team',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_at_bats',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_batting_average',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_doubles',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_hits',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_home_runs',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_runs',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_triples',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wins',
        ),
        migrations.AddIndex(
            model_name='league',
            index=models.Index(fields=['league_name'], name='League_App__league__ff9f2b_idx'),
        ),
    ]
