# Generated by Django 4.0.4 on 2022-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('League_App', '0009_remove_player_first_name_player_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='at_bats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='batting_average',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='player',
            name='chances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='doubles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='fielding_percentage',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='player',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='home_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='putouts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='singles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='triples',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
