# Generated by Django 4.0.4 on 2022-04-20 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League_App', '0010_player_assists_player_at_bats_player_batting_average_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name_plural': 'players'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'teams'},
        ),
        migrations.RemoveIndex(
            model_name='league',
            name='League_App__league__ff9f2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='player',
            name='League_App__last_na_11960d_idx',
        ),
        migrations.RemoveIndex(
            model_name='team',
            name='League_App__team_na_2a0b90_idx',
        ),
        migrations.RemoveField(
            model_name='team',
            name='t_players',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='League_App.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='League_App.league'),
        ),
    ]
