# Generated by Django 4.0.4 on 2022-04-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('League_App', '0012_remove_player_batting_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='League_App.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='league', to='League_App.league'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='My Team', max_length=200),
        ),
    ]
